#!/bin/sh /etc/rc.common

START=95

start() {
    [ -e /etc/overlay_setup_done ] && exit 0

    MMC_DEV="/dev/mmcblk0p1"
    MNT_DIR="/mnt"

    # 检查设备是否存在
    [ ! -b "$MMC_DEV" ] && logger "overlay-setup: No $MMC_DEV" && exit 1

    # 检查是否已经是 ext4，如果不是就格式化
    MMC_FS=$(blkid -s TYPE -o value "$MMC_DEV")
    if [ "$MMC_FS" != "ext4" ]; then
        mkfs.ext4 -F "$MMC_DEV"
    fi

    # 挂载临时目录
    mkdir -p "$MNT_DIR"
    mount "$MMC_DEV" "$MNT_DIR" || exit 1

    # 配置 fstab（第一次写入）
    uci batch <<EOF
set fstab.@mount[0]=mount
set fstab.@mount[0].target='/overlay'
set fstab.@mount[0].uuid='$(blkid -s UUID -o value "$MMC_DEV")'
set fstab.@mount[0].enabled='1'
set fstab.@mount[0].fstype='ext4'
set fstab.@mount[0].options='defaults'
EOF
    uci commit fstab

    # 标记设置完成
    touch /etc/overlay_setup_done

    logger "overlay-setup: TF卡配置完成，系统将自动重启..."
    sleep 3
    reboot
}
