name: Build MW4530R OpenWrt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt v24.10.2
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: main
      

      - name: Patch DTS + image template for 16MB flash
        run: |
          sed -i 's/reg = <0x020000 0x7d0000>;/reg = <0x020000 0xfe0000>;/' target/linux/ath79/dts/ar9344_tplink_tl-wdrxxxx.dtsi
          sed -i 's/reg = <0x7f0000 0x010000>;/reg = <0xff0000 0x010000>;/' target/linux/ath79/dts/ar9344_tplink_tl-wdrxxxx.dtsi
          sed -i '/define Device\/mercury_mw4530r-v1/,/^endef/ s/$(Device\/tplink-8mlzma)/$(Device\/tplink-16mlzma)/' target/linux/ath79/image/generic.mk

      - name: Update feeds and install
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare .config
        run: |
          cat > .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_ath79_generic_DEVICE_mercury_mw4530r-v1=y
          EOF

          make defconfig

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: |
            dl
            build_dir
          key: openwrt-${{ github.run_id }}

      - name: Build firmware
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: MW4530R-Firmware
          path: bin/targets/ath79/generic/*.bin
