name: Build OpenWrt MW4530R USB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10

      - name: Patch DTS & image template (16MB flash, Wi-Fi enabled)
        run: |
          # 扩展闪存分区
          sed -i 's/reg = <0x020000 0x7d0000>;/reg = <0x020000 0xfe0000>;/' target/linux/ath79/dts/ar9344_tplink_tl-wdrxxxx.dtsi
          sed -i 's/reg = <0x7f0000 0x010000>;/reg = <0xff0000 0x010000>;/' target/linux/ath79/dts/ar9344_tplink_tl-wdrxxxx.dtsi

          # 修改 image 模板为 16MB
          sed -i '/define Device\/mercury_mw4530r-v1/,/^endef/ s/$(Device\/tplink-8mlzma)/$(Device\/tplink-16mlzma)/' target/linux/ath79/image/generic.mk

          # 移除 art 分区的只读标志
          sed -i '/label = "art";/,/};/s/^\s*read-only;\s*$//' target/linux/ath79/dts/ar9344_tplink_tl-wdrxxxx.dtsi


      - name: Add uci-defaults script to enable wifi by default
        run: |
          mkdir -p files/etc/uci-defaults
          cat > files/etc/uci-defaults/99_enable_wifi <<EOF
          #!/bin/sh
          uci set wireless.@wifi-device[0].disabled=0
          uci set wireless.@wifi-iface[0].disabled=0
          uci set wireless.@wifi-device[1].disabled=0
          uci set wireless.@wifi-iface[1].disabled=0
          uci commit wireless
          EOF
          chmod +x files/etc/uci-defaults/99_enable_wifi
  
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Inject custom config
        run: |
          cat >> .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_generic=y
          CONFIG_TARGET_ath79_generic_DEVICE_mercury_mw4530r-v1=y

          CONFIG_PACKAGE_base-files=y
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_dnsmasq=y
          CONFIG_PACKAGE_dropbear=y
          CONFIG_PACKAGE_firewall4=y
          CONFIG_PACKAGE_fstools=y
          CONFIG_PACKAGE_kmod-ath9k=y
          CONFIG_PACKAGE_kmod-gpio-button-hotplug=y
          CONFIG_PACKAGE_kmod-nft-offload=y
          CONFIG_PACKAGE_libc=y
          CONFIG_PACKAGE_libgcc=y
          CONFIG_PACKAGE_libustream-mbedtls=y
          CONFIG_PACKAGE_logd=y
          CONFIG_PACKAGE_mtd=y
          CONFIG_PACKAGE_netifd=y
          CONFIG_PACKAGE_nftables=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_opkg=y
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y
          CONFIG_PACKAGE_procd-ujail=y
          CONFIG_PACKAGE_swconfig=y
          CONFIG_PACKAGE_uboot-envtools=y
          CONFIG_PACKAGE_uci=y
          CONFIG_PACKAGE_uclient-fetch=y
          CONFIG_PACKAGE_urandom-seed=y
          CONFIG_PACKAGE_urngd=y
          CONFIG_PACKAGE_wpad-basic-mbedtls=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb-ledtrig-usbport=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y

          # USB 上网支持
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-ipheth=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-serial=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          CONFIG_PACKAGE_kmod-usb-serial-wwan=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_usbutils=y
          CONFIG_PACKAGE_umbim=y
          CONFIG_PACKAGE_wwan=y
          CONFIG_PACKAGE_luci-proto-ppp=y
          CONFIG_PACKAGE_luci-proto-qmi=y
          CONFIG_PACKAGE_luci-proto-ncm=y
          EOF

          make defconfig

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: dl
          key: openwrt-${{ github.run_id }}

      - name: Build firmware
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-mw4530r-usb
          path: bin/targets/ath79/generic/*.bin
