name: Build OpenWrt JDCloud RE-CP-02

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file wget python3

      - name: Clone OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git -b master openwrt
          cp jdcloud.config openwrt/.config
          cp -r files openwrt/

      - name: Update and install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile Firmware
        working-directory: ./openwrt
        run: |
          make defconfig
          make download -j8
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: JDCloud_RECP02_Firmware
          path: openwrt/bin/targets/
