CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_jdcloud_re-cp02=y

# 语言与 LuCI
CONFIG_LUCI_LANG_zh_Hans=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_luci-ssl=y

# 挂载与文件系统支持
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_fstab=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-fs-vfat=y
CONFIG_PACKAGE_kmod-fs-exfat=y
CONFIG_PACKAGE_kmod-mmc=y
CONFIG_PACKAGE_kmod-sdhci=y
CONFIG_PACKAGE_kmod-sdhci-mt7620=y
CONFIG_PACKAGE_e2fsprogs=y
CONFIG_PACKAGE_fdisk=y
CONFIG_PACKAGE_lsblk=y
CONFIG_PACKAGE_blkid=y

# Wi-Fi及Mesh支持
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_PACKAGE_luci-app-wireless-regdb=y
CONFIG_PACKAGE_wpad-basic-mbedtls=y
CONFIG_PACKAGE_wpad-mesh-openssl=y
CONFIG_PACKAGE_luci-app-meshwizard=y

# Samba支持
CONFIG_PACKAGE_samba4-server=y
CONFIG_PACKAGE_luci-app-samba4=y

# IPv6 完整支持
CONFIG_IPV6=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_kmod-ipv6=y
CONFIG_PACKAGE_kmod-nf-conntrack6=y
CONFIG_PACKAGE_kmod-nf-reject6=y
CONFIG_PACKAGE_kmod-sit=y
CONFIG_PACKAGE_kmod-ip6tables=y

# 系统工具
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_vim-full=y
CONFIG_PACKAGE_luci-app-commands=y

# 关闭调试编译符号，加快编译
CONFIG_DEBUG=n
CONFIG_KERNEL_DEBUG_INFO=n
CONFIG_STRIP_KERNEL_EXPORTS=y
CONFIG_KERNEL_PRINTK=y
