name: Build OpenWrt for JDCloud RE-CP-02 (MT7621)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Clone immortalwrt source
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git -b openwrt-23.05 openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom .config
        run: |
          mkdir -p openwrt
          cat <<EOF > openwrt/.config
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_phicomm_k2p=y

# TF 卡支持（MMC）
CONFIG_PACKAGE_kmod-mmc=y
CONFIG_PACKAGE_kmod-sdhci=y
CONFIG_PACKAGE_kmod-sdhci-mt7620=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_fdisk=y
CONFIG_PACKAGE_e2fsprogs=y

# Mesh / 无线支持
CONFIG_PACKAGE_wpad-mesh-openssl=y
CONFIG_PACKAGE_iw=y
CONFIG_PACKAGE_luci-proto-mesh=y

# LuCI Web
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-mount=y
CONFIG_PACKAGE_luci-app-ttyd=y

# 常用实用工具
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_screen=y
CONFIG_PACKAGE_curl=y
EOF

      - name: Download and install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Make defconfig
        run: |
          cd openwrt
          make defconfig

      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-JDCloud-RE-CP-02
          path: openwrt/bin/targets/
