name: Build OpenWrt for JDCloud RE-CP-02

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout immortalwrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-23.05

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
        rsync subversion swig time unzip wget zlib1g-dev

    - name: Load custom config
      run: |
        curl -Lo .config https://raw.githubusercontent.com/${{ github.repository }}/main/jdcloud.config

    - name: Make defconfig
      run: make defconfig

    - name: Build
      run: make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: bin/targets/
