name: Build JDCloud RE-CP-02 Minimal OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3-setuptools

      - name: Clone LEDE
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          cat > .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_jdcloud_re-cp02=y

          CONFIG_TARGET_ROOTFS_SQUASHFS=y

          # Web 管理界面
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-firewall=y

          # 基础常用功能
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y
          CONFIG_PACKAGE_wget-ssl=y
          CONFIG_PACKAGE_curl=y

          EOF

          make defconfig

      - name: Cache DL
        uses: actions/cache@v4
        with:
          path: dl
          key: lede-dl-${{ hashFiles('.config') }}

      - name: Build Firmware
        run: |
          cd lede
          make -j$(nproc)

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: JDCloud-RECP02-Firmware
          path: lede/bin/targets/ramips/mt7621/*sysupgrade*.bin
